title:             Matemática - Licenciatura  
email:             maf172.teste@gmail.com
description:       Página mantida por alunos da disciplina MAF 172 - Matemática Computacional
author:            J
#url:               "localhost:4000"
url:               "http://maf172-teste.github.io/"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          11
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
